/**
 * Generated by tsnapi — public API snapshot of `@luxass/utils/guards`
 */
// #region Functions
export declare function isNotNull<T>(_: T | null): v is Exclude<T, null>;
export declare function isNotNullish<T>(_: T | null | undefined): v is NonNullable<T>;
export declare function isNotUndefined<T>(_: T): v is Exclude<T, undefined>;
export declare function isTruthy<T>(_: T): v is NonNullable<T>;
// #endregion