/**
 * Generated by tsnapi — public API snapshot of `@luxass/utils`
 */
// #region Classes
export declare class InvariantError extends Error {
  readonly message: string;
  constructor(_: string, ..._: any[]);
}
// #endregion

// #region Functions
export declare function invariant(_: unknown, _: string, ..._: unknown[]): asserts predicate;
// #endregion

// #region Other
export { appendTrailingSlash }
export { capitalize }
export { clamp }
export { dedent }
export { dedentRaw }
export { ElementOf }
export { formatStr }
export { getChangedKeys }
export { getOwnProperty }
export { hasOwnProperty }
export { InferArguments }
export { isNotNull }
export { isNotNullish }
export { isNotUndefined }
export { isTruthy }
export { omit }
export { prependLeadingSlash }
export { Prettify }
export { pRetry as promiseRetry }
export { RemoveIndexSignature }
export { sanitizeIdentifier }
export { toCamelCase }
export { toKebabCase }
export { toPascalCase }
export { toSnakeCase }
export { trimLeadingSlash }
export { trimTrailingSlash }
// #endregion