/**
 * Generated by tsnapi — public API snapshot of `@luxass/utils/object`
 */
// #region Functions
export declare function getChangedKeys<T extends object>(_: T, _: T): (keyof T)[];
export declare function getOwnProperty<K extends string, V>(_: Partial<Record<K, V>>, _: K): V | undefined;
export declare function getOwnProperty<O extends object>(_: O, _: string): O[keyof O] | undefined;
export declare function getOwnProperty(_: object, _: string): unknown;
export declare function hasOwnProperty(_: object, _: string): boolean;
export declare function omit(_: Record<string, unknown>, _: ReadonlyArray<string>): Record<string, unknown>;
// #endregion