/**
 * Generated by tsnapi — public API snapshot of `@luxass/utils/path`
 */
// #region Functions
export declare function appendTrailingSlash(_: string | undefined): string;
export declare function joinURL(_: string, ..._: string[]): string;
export declare function prependLeadingSlash(_: string | undefined): string;
export declare function trimLeadingSlash(_: string | undefined): string;
export declare function trimTrailingSlash(_: string | undefined): string;
// #endregion