/**
 * Generated by tsnapi — public API snapshot of `@luxass/utils/string`
 */
// #region Functions
export declare function capitalize(_: string): string;
export declare function dedent(_: string): string;
export declare function dedent(_: TemplateStringsArray, ..._: unknown[]): string;
export declare function dedentRaw(_: string): string;
export declare function dedentRaw(_: TemplateStringsArray, ..._: unknown[]): string;
export declare function formatStr(_: string, ..._: unknown[]): string;
export declare function sanitizeIdentifier(_: string): string;
export declare function toCamelCase(_: string): string;
export declare function toKebabCase(_: string): string;
export declare function toPascalCase(_: string): string;
export declare function toSnakeCase(_: string): string;
// #endregion